### ISSUE TITLE
[Feat] 공통 컴포넌트 구현

### ISSUE THREAD

**Issue by kongnayeon** [CEOS-Developers/CEOS-FE#3]
### ✏️ 기능 개요

공통으로 사용되는 컴포넌트 개발

### ✅ TODO - CEOS

- [x] 나연: 버튼1, 버튼2, 바로가기 버튼, 선택지 버튼
- [x] 효정: 텍스트 필드 소, 대
- [x] #5
- [x] #7
- [x] 선호: 헤더, FAQ 박스

### ✅ TODO - ADMIN

- [x] 지은: 리워드카드, 프로젝트카드, 활동카드, 스폰서카드
- [x] 나연: 데이트피커, 이미지 업로드
