### ISSUE TITLE
[Feat] CEOS 화면 단위 기능 구현

### ISSUE THREAD

**Issue by YooSeonHo** [CEOS-Developers/CEOS-FE#30]
### ✏️ 기능 개요
 유저 페이지를 화면 단위로 나누어 기능을 구현합니다.

### ✅ TODO
선호 : 
- [x] 레이아웃
- [x] 랜딩 페이지
- [x] 리쿠르팅 - 랜딩
- [x] 리쿠르팅 - 합격자 발표

지은 :
- [x] 프로젝트 페이지
- [x] 활동 페이지
- [x] FAQ 페이지
- [x] 리쿠르팅 - 지원서

### 프로젝트 남은 Task
- [x] 프로젝트 카드 선택 시 뜨는 모달 레이아웃
- [x] 모달에 띄울 데이터 fetch
- [x] 데이터 동적으로 렌더링해서 띄우기

### 리쿠르팅 남은 Task
```
각 data 정확한 양식 확인 -> 유효성 처리 필요
폼 전체 입력시에만 button 색 변환
모바일에서 '다음' 버튼 작업 필요
```
- [x] 백엔드 에러 메시지 alert
- [x] 모바일에서 버튼 선택시 버튼색 변하지 않는 문제 해결
- [x] '불가능한 시간 없음' 시 데이터 어떻게 처리하는지 확인 필요
- [x] 지원완료시 모달 띄우는 작업 필요
- [x] 불가능한시간 없음 데이터 형식 확인하기

### 검토 필요한 Task
- [x] Footer에 할당된 svg 크기 맞추기
- [x] InfiniteQuery 적용
- [x] api 내 이미지 연결
