### ISSUE TITLE
[Feat] Admin 화면 구현

### ISSUE THREAD

**Issue by jhj2713** [CEOS-Developers/CEOS-FE#42]
### ✏️ 기능 개요
admin 화면 구현

### ✅ TODO
효정
- [x] FAQ 페이지
- [x] Recruit 페이지
- [x] 지원서 제출 페이지

나연
- [x] 페이지 수정 - Management
- [x] 페이지 수정 - Reward
- [x] 페이지 수정 - Activity
- [x] 페이지 수정 - Sponsored by

채연
- [x] 레이아웃 (로그인 페이지 조건부여 필요)
- [x] 로그인 페이지
- [x] 지원현황 페이지
- [x] 유저관리 페이지
- [x] 페이지 수정 - Project
